// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/telemetry.proto

package telemetrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Pid                 int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ExecutableName      string                 `protobuf:"bytes,2,opt,name=executable_name,json=executableName,proto3" json:"executable_name,omitempty"`
	ResourceUtilization float64                `protobuf:"fixed64,3,opt,name=resource_utilization,json=resourceUtilization,proto3" json:"resource_utilization,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetExecutableName() string {
	if x != nil {
		return x.ExecutableName
	}
	return ""
}

func (x *ProcessInfo) GetResourceUtilization() float64 {
	if x != nil {
		return x.ResourceUtilization
	}
	return 0
}

type TelemetryPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuUtilization    float64                `protobuf:"fixed64,2,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`
	MemoryUtilization float64                `protobuf:"fixed64,3,opt,name=memory_utilization,json=memoryUtilization,proto3" json:"memory_utilization,omitempty"`
	DiskIo            float64                `protobuf:"fixed64,4,opt,name=disk_io,json=diskIo,proto3" json:"disk_io,omitempty"`
	NetworkIngress    float64                `protobuf:"fixed64,5,opt,name=network_ingress,json=networkIngress,proto3" json:"network_ingress,omitempty"`
	NetworkEgress     float64                `protobuf:"fixed64,6,opt,name=network_egress,json=networkEgress,proto3" json:"network_egress,omitempty"`
	Temperature       float64                `protobuf:"fixed64,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Uptime            int32                  `protobuf:"varint,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Status            string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	TopProcesses      []*ProcessInfo         `protobuf:"bytes,10,rep,name=top_processes,json=topProcesses,proto3" json:"top_processes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetryPayload) Reset() {
	*x = TelemetryPayload{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPayload) ProtoMessage() {}

func (x *TelemetryPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPayload.ProtoReflect.Descriptor instead.
func (*TelemetryPayload) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryPayload) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TelemetryPayload) GetCpuUtilization() float64 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *TelemetryPayload) GetMemoryUtilization() float64 {
	if x != nil {
		return x.MemoryUtilization
	}
	return 0
}

func (x *TelemetryPayload) GetDiskIo() float64 {
	if x != nil {
		return x.DiskIo
	}
	return 0
}

func (x *TelemetryPayload) GetNetworkIngress() float64 {
	if x != nil {
		return x.NetworkIngress
	}
	return 0
}

func (x *TelemetryPayload) GetNetworkEgress() float64 {
	if x != nil {
		return x.NetworkEgress
	}
	return 0
}

func (x *TelemetryPayload) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TelemetryPayload) GetUptime() int32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *TelemetryPayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TelemetryPayload) GetTopProcesses() []*ProcessInfo {
	if x != nil {
		return x.TopProcesses
	}
	return nil
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\ttelemetry\"{\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12'\n" +
	"\x0fexecutable_name\x18\x02 \x01(\tR\x0eexecutableName\x121\n" +
	"\x14resource_utilization\x18\x03 \x01(\x01R\x13resourceUtilization\"\xfd\x02\n" +
	"\x10TelemetryPayload\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0fcpu_utilization\x18\x02 \x01(\x01R\x0ecpuUtilization\x12-\n" +
	"\x12memory_utilization\x18\x03 \x01(\x01R\x11memoryUtilization\x12\x17\n" +
	"\adisk_io\x18\x04 \x01(\x01R\x06diskIo\x12'\n" +
	"\x0fnetwork_ingress\x18\x05 \x01(\x01R\x0enetworkIngress\x12%\n" +
	"\x0enetwork_egress\x18\x06 \x01(\x01R\rnetworkEgress\x12 \n" +
	"\vtemperature\x18\a \x01(\x01R\vtemperature\x12\x16\n" +
	"\x06uptime\x18\b \x01(\x05R\x06uptime\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12;\n" +
	"\rtop_processes\x18\n" +
	" \x03(\v2\x16.telemetry.ProcessInfoR\ftopProcesses\"G\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xae\x01\n" +
	"\x10TelemetryService\x12J\n" +
	"\rSendTelemetry\x12\x1b.telemetry.TelemetryPayload\x1a\x1c.telemetry.TelemetryResponse\x12N\n" +
	"\x0fStreamTelemetry\x12\x1b.telemetry.TelemetryPayload\x1a\x1c.telemetry.TelemetryResponse(\x01B\x15Z\x13./proto/telemetrypbb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_telemetry_proto_goTypes = []any{
	(*ProcessInfo)(nil),       // 0: telemetry.ProcessInfo
	(*TelemetryPayload)(nil),  // 1: telemetry.TelemetryPayload
	(*TelemetryResponse)(nil), // 2: telemetry.TelemetryResponse
}
var file_proto_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.TelemetryPayload.top_processes:type_name -> telemetry.ProcessInfo
	1, // 1: telemetry.TelemetryService.SendTelemetry:input_type -> telemetry.TelemetryPayload
	1, // 2: telemetry.TelemetryService.StreamTelemetry:input_type -> telemetry.TelemetryPayload
	2, // 3: telemetry.TelemetryService.SendTelemetry:output_type -> telemetry.TelemetryResponse
	2, // 4: telemetry.TelemetryService.StreamTelemetry:output_type -> telemetry.TelemetryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
